<?php

namespace App\Http\Controllers\Dashboard\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Size;
use App\Models\ProductSize;
use App\Models\ProductImage;
use Illuminate\Support\Facades\Storage;

class AdminProductController extends Controller
{
    // Show all products
    public function index()
    {

     $totalProducts = Product::count(); // Count all products 
     $products = Product::with('brand', 'category', 'images')->paginate(10);

     return view('dashboard.admin.products.index', compact('products'));
    }

    public function brands($category_id)
    {
      $brands =Brand::where('category_id', $category_id)->get();

     return response()->json($brands);
   }

    //get sizes with gender
    public function getSizes($gender)
    {
        $sizes = Size::where('gender', $gender)->get();

        return response()->json($sizes);
    }

    // Show add product form
   public function create()
    {
        $categories = Category::orderBy('name')->get();
        $brands = Brand::orderBy('name')->get();

        return view('dashboard.admin.products.create', compact(
            'categories',
            'brands'
        ));
    }


    // Store product + multiple images
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|string|max:255|unique:products,name',
            'description' => 'nullable|string',
            'price' => 'required|numeric',
            'category_id' => 'required|exists:categories,id',
            'brand_id' => 'required|exists:brands,id',
            'gender' => 'required|string|max:255',
            // ⭐ Sizes validation
            'sizes' => 'required|array|min:1',
            'sizes.*' => 'exists:sizes,id',
            //✅ Validate the array itself
            'images' => 'required|array|min:1',
            //✅ Validate each file inside the array
           'images.*' => 'image|mimes:jpeg,png,jpg,gif|max:2048',
           // Flags validation (optional, boolean)
           'is_trending' => 'nullable|boolean',
           'is_new_arrival' => 'nullable|boolean',
           'status' => 'required|in:active,inactive',
        ]);

        // Set default 0 if checkbox is not selected
        $data['is_trending'] = $request->has('is_trending') ? 1 : 0;
        $data['is_new_arrival'] = $request->has('is_new_arrival') ? 1 : 0;
     
        // Create product slug auto-generated by model
        $product = Product::create($data);

        // ⭐ Save Multiple Sizes
       // Sync sizes
       $product->sizes()->sync($request->sizes);

        // Handle multiple images
        if ($request->hasFile('images')) {
            foreach ($request->file('images') as $file) {
                $upload = uploadImage($file, 'products', true, [300, 300]);
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_path' => $upload['image'],
                    'image_thumb' => $upload['thumbnail']
                ]);
            }
        }

        return redirect()->route('admin.products.index')->with('success', 'Product added successfully!');
    }

    // Show edit form
    public function edit($id)
    {
        $product = Product::with('images')->findOrFail($id);
        $categories = Category::orderBy('name')->get();
        $brands = Brand::orderBy('name')->get();
        // Product ke selected size IDs
        $selectedSizes = $product->sizes->pluck('id')->toArray();

        return view('dashboard.admin.products.edit', compact('product', 'categories', 'brands','selectedSizes'));
    }

    // Update product + images
    public function update(Request $request, $id)
    {
    $product = Product::findOrFail($id);

    $validated = $request->validate([
        'name'        => 'required|string|max:255|unique:products,name,' . $product->id,
        'category_id' => 'required|exists:categories,id',
        'brand_id'    => 'required|exists:brands,id',
        'gender' => 'required|string|max:255',
        'sizes' => 'required|array|min:1', // at least one size
        'sizes.*' => 'exists:sizes,id',
        'price'       => 'required|numeric',
        'description' => 'nullable|string',
        'images.*'    => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
         // Product Flags
        'is_trending'     => 'nullable|boolean',
        'is_new_arrival'  => 'nullable|boolean',
        'status' => 'required|in:active,inactive',
    ]);

    // ✅ Additional check: Ensure at least one image exists overall
    $hasExistingImages = $product->images()->exists();
    $hasNewImages = $request->hasFile('images');

    if (!$hasExistingImages && !$hasNewImages) {
        return back()
            ->withErrors(['images' => 'Please upload at least one image.'])
            ->withInput();
    }

    // Handle flags (checkbox sends null if unchecked)
    $validated['is_trending'] = $request->has('is_trending') ? 1 : 0;
    $validated['is_new_arrival'] = $request->has('is_new_arrival') ? 1 : 0;

    // Update main product info slug auto-updated by model
    $product->update($validated);

    // Append new images if any
    if ($request->hasFile('images')) {
        foreach ($request->file('images') as $imageFile) {
            $upload = uploadImage($imageFile, 'products', true, [150, 150]);
            $product->images()->create([
                'image_path'  => $upload['image'],
                'image_thumb' => $upload['thumbnail'],
            ]);
        }
    }

    // Sync sizes with pivot table
    // If you want stock too, you can pass ['size_id' => ['stock' => value]]
    $product->sizes()->sync($request->sizes);

    return redirect()->route('admin.products.index')
        ->with('success', 'Product updated successfully!');
}

    // Delete product + all images
    public function destroy($id)
    {
        $product = Product::with('images')->findOrFail($id);

        foreach ($product->images as $img) {
            if ($img->image_path && Storage::exists('public/' . $img->image_path)) {
                Storage::delete('public/' . $img->image_path);
            }
            if ($img->image_thumb && Storage::exists('public/' . $img->image_thumb)) {
                Storage::delete('public/' . $img->image_thumb);
            }
            $img->delete();
        }

        $product->delete();

        return redirect()->route('admin.products.index')->with('success', 'Product deleted successfully!');
    }

        public function deleteImage($id)
        {
            $image = \App\Models\ProductImage::find($id);

            if (!$image) {
                return response()->json([
                    'success' => false,
                    'message' => 'Image not found!'
                ]);
            }

            if ($image->image_path && \Storage::exists('public/' . $image->image_path)) {
                \Storage::delete('public/' . $image->image_path);
            }

            if ($image->image_thumb && \Storage::exists('public/' . $image->image_thumb)) {
                \Storage::delete('public/' . $image->image_thumb);
            }

            $image->delete();

            return response()->json([
                'success' => true,
                'message' => 'Image deleted successfully!'
            ]);
        }


}
